version: "3.9"

services:
  # === Рабочее приложение ===
  ingest_events_app:
    build: .
    container_name: ingest_events_app
    ports:
      - "8000:8000"
    volumes:
      - ./data/sample:/app/data
      - ./event_db_data:/app/event_service/event_db_data
    environment:
      - IMPORT_ON_START=true
    command: uvicorn event_service.main:app --host 0.0.0.0 --port 8000

  # === Тестовое приложение ===
  ingest_events_test:
    build: .
    container_name: ingest_events_test
    ports:
      - "8001:8001"
    volumes:
      - ./data/test:/app/data
      - ./event_db_data:/app/event_service/event_db_data
    environment:
      - IMPORT_ON_START=true
      - TEST_MODE=1
    command: uvicorn event_service.main:app --host 0.0.0.0 --port 8001

  # === Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    depends_on:
      - ingest_events_app

  # === Grafana ===
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # === Тесты ===
  tests:
    build: .
    environment:
      - TEST_MODE=1
    command: pytest -v
    volumes:
      - .:/app
    depends_on:
      - ingest_events_test
